name: Download and Archive

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'Url'
        required: true
        type: string
      archive_password:
        description: 'Password'
        required: false
        type: string
      cookies:
        description: 'Cookies'
        required: false
        type: string

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Mask Password
        run: |
          PSWD=$(jq -r '.inputs.archive_password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PSWD
          echo PSWD=$PSWD >> $GITHUB_ENV
      - name: Mask Url
        run: |
          URL=$(jq -r '.inputs.download_url' $GITHUB_EVENT_PATH)
          echo ::add-mask::$URL
          echo URL=$URL >> $GITHUB_ENV
      - name: Mask Cookies
        run: |
          COOKIES=$(jq -r '.inputs.cookies' $GITHUB_EVENT_PATH)
          echo ::add-mask::$COOKIES
          echo COOKIES=$COOKIES >> $GITHUB_ENV

      - name: Run downloader
        run: |
          node downloader.js "${{ env.URL }}" "${{ env.PSWD }}" "${{ env.COOKIES }}"

      - name: Commit and Push files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.7z*
          git commit -m "Add downloaded archive parts"
          git push
